#!/usr/bin/env bash

readonly pwdir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
readonly dbdir="${DBDIR:-${pwdir}/db.d}"
readonly image="${IMAGE:-crunchydata/crunchy-postgres-gis:centos7-10.3-1.8.2}"
readonly dbname="${DB:-events}"
readonly username="${USER:-user}"
readonly password="${PASS:-pass}"
readonly port=5432

start() {
  docker run "$@" \
    -p "$port:$port" \
    -e PG_MODE=primary \
    -e PG_DATABASE="$dbname" \
    -e PG_ROOT_PASSWORD=postgres \
    -e PG_PRIMARY_USER="$username" \
    -e PG_PRIMARY_PASSWORD="$password" \
    -e PG_USER=postgres \
    -e PG_PASSWORD=postgres \
    -e PG_PRIMARY_PORT="$port" \
    -v ${dbdir}:/docker-entrypoint-initdb.d \
    ${image}
}

restart() {
  docker start -i "$1"
}

"$@"
